### ISSUE TITLE
Нужно получить notnull сессию из DbSessionConsumer

### ISSUE THREAD

**Issue by Rinatich** [Byndyusoft/Byndyusoft.Data.Relational#13]
Сейчас может вернуться null, когда я хочу получить сессию. Не хотелось бы проверять в каждом запросе репозитория на null. 
1. Может, добавить свойство NullableSession, а просто в свойстве Session проверять на null в самом свойстве. 
2. Или наоборот добавить свойство NotNullableSession, но тогда придется использовать это длинное наименование в каждом свойстве.
Я за 1-й вариант.

**Comment by govorovvs** [comment]
fixed in 0.8.0
